theleagueof/fontship

Dockerfile
Local builds still have been working, but Docker Hub did something to their filesystems that fresh GNU coreutils is very unhappy about. This is a standby until [the upstream issue](https://github.com/archlinux/archlinux-docker/issues/32) is fixed.
=> Patch up Docker Hub builds

.github/workflows/build.yml
I did a bad. I push some stuff to master that Worked For Me™. Why I was tired and grumpy and just did it anyway is a story for another day. This PR is to fix what broke, mainly CI not having the same environment as my local machine and hence failing to build.
=> Install system, Python & module dependencies before build in CI

fontship.in
This is for easy migration of repositories to start using Fontship **now** before it starts doing anything fancy my providing a migration path for existing build scripts such that functionality can be swapped out piece by piece.
=> Punt build operations to existing build scripts

src/rules.mk
Most of these rules originate from refactoring the League Spartan `build.sh` script as make rules.
=> Rules rules rules

src/rules.mk
This mostly just tidies up the files so that intermediate things designers should not be concerned with in most cases are in a hidden build directory.
Functionally it also allows building groups of fonts by either output format (ttf, otf, etc.) or by type (static, variable).
=> Tidy up the builds process

Dockerfile, Makefile.am, build-aux/docker-entrypoint.sh
This 'hack' is useful in a few rare cases, but also causes a lot of
problems (e.g. Can't run `fontship -q make` without it eating
arguments). The most useful thing is getting a bash shell in the
container, but that can actually be done with a docker command line
argument too. Best just to force our CLI unless the user is very
specific about doing otherwise — least surprise.
=> chore: Drop fancy Docker entry point hack

fontship.in, src/functions.mk, src/rules-glyphs.mk, src/rules-sfd.mk, src/rules-ufo.mk, src/rules.mk
This is a significant overhaul to how rules are organized so that they can be over-written on a per-project bases as need arises. New source formats can even be handled just by supplying templates to build instances.
Output formats can also be controlled.
Now defaults to assuming sources are in `sources/*` unless otherwise specified, per discussion in #47.
All settings are currently make variables, pending discussion in #21.
=> Allow multiple family names per project

Makefile.am, src/rules.mk
Sampling builds of Libertinus (6.8 MB of raw OTF files):
```console
.rw-r--r--  3.1M caleb 13 Aug  0:37  Libertinus-1.111.tar.bz2
.rw-r--r--  3.3M caleb 13 Aug  0:38  Libertinus-1.111.tar.gz
.rw-r--r--  1.8M caleb 13 Aug  0:37  Libertinus-1.111.tar.xz
.rw-r--r--  2.6M caleb 13 Aug  0:37  Libertinus-1.111.tar.zst
.rw-r--r--  3.3M caleb 13 Aug  0:37  Libertinus-1.111.zip
```
Since XZ compression is almost universally supported by any tar in the neighborhood, the 2× better compression just makes sense.
=> Change output compression from gz to xz

src/rules-sfd.mk, src/rules.mk
Allow prefixes like `v...`, and allow big version numbers with two digit majors like `12.000`.
=> Handle font versioning better

src/rules.mk
The `#` is a start-of-comment character in Makefiles.  This commit changes sed to use `,` instead, as otherwise things break with
unterminated call to function 'notdir': missing ')'.  Stop.
=> Use ‘,’ instead of ‘#’ as delimiter in sed’s “s” command

.github/workflows/build.yml, .github/workflows/superlinter.yml, Dockerfile, Makefile.am, fontship.in, requirements.txt, src/fontship.mk, src/functions.mk, src/rules.mk
This is part of a series of PR's working on builds from UFO (and later mixed with Glyphs) sources fixing issues that come up while I work through [deforking Raleway](https://github.com/theleagueof/raleway/pull/16). See previously #68.
=> Raleway to heaven [part 2]

src/rules.mk
Closes #27 
More can be added as needed, but this covers the most common standard names. Projects can override the variable as well.
=> Find and package authors, contributors, and fontlog files

src/rules.mk
Not all font projects even generate TTFs, and in the cases where they generate both, the OTFs are usually a better candidate for compression to webfonts due to having more access to OpenType features.
=> feat(woff): Generate webfonts from OTF if possible, fallback to TTF

.github/workflows/superlinter.yml, README.md, build-aux/git-version-gen
Bad is when your linter finds its *own* code and throws lint errors.
Superlinter is a cool idea, but the fact that it's a moving target and they keep botching new releases over and over again with stuff that just doesn't work out of the box is starting to drive we toward implementing the linters I want piecemeal.
=> Make super-linter less bad

src/rules.mk
This reverses the logic from #85 to default to building webfonts from TTF and only falling back to OTF if they are not available.
=> Default to building webfonts from TTF, but fallback to OTF

src/rules-glyphs.mk, src/rules-ufo.mk
With GNU Make's variable evaluation, one temporary file was getting
created during the eval, and another one created (and removed) during
the cleanup. Only allowing the variable to evaluate once should solve
that.
Closes #75.
=> fix(rules): Remove the same TMP file we create, not a different one

Makefile.am, assets/en-US/cli.ftl, make-shell.zsh, rules/fontship.mk, rules/rules.mk, src/lib.rs, src/make/mod.rs
Closes #99.
This is sorcery. Serious dark arts stuff: evals in subshells, z-shell multios, async subprocess stream capturing, and boiled newt toes. Well okay maybe not that last one. Seriously though the result is the most **informative and pretty** insights into to GNU Make I've ever seen, to the point where now I want to spin this off as a separate project! It's like a user friendly color UI giving you just the TL;DR; bits that [`remake --trace`](http://bashdb.sourceforge.net/remake/) could have told you if you liked `gdb`.
The short version is that the CLI is now a full blown orchestration wrapper around `make` that watches the output of parallel jobs, reports job stop and starts with a pretty interface, and only dumps more verbose content if there is a problem.
=> Wrap output of make jobs

assets/en-US/cli.ftl, src/cli.rs
Currently, the generated zsh compdef contains something along the
lines of
```zsh
(( $+functions[_fontship_commands] )) ||
_fontship_commands() {
local commands; commands=(
"make:Build specified target(s) with `make`" \
"setup:Configure a font project repository" \
"status:Show status information about setup, configuration, and build state" \
"help:Prints this message or the help of the given subcommand(s)" \
)
_describe -t commands 'fontship commands' commands "$@"
}
```
I.e., it performs command substitution on ‘make’, which in the best
case fails with something along the lines of “make: *** No targets
specified and no makefile found.  Stop.” and in the worst case ends up
running ‘make’ for you.
This issue should probably be brought up to clap-rs/clap so that it is
made to use single …
=> fix(cli): Don’t use backticks to unbreak zsh compdef

assets/en-US/cli.ftl, rules/fontship.mk, rules/functions.mk, rules/rules.mk, src/lib.rs, src/setup/mod.rs
This doesn't do as much error checking as will be necessary eventually before doing more monkeying with Git internals, but I think it does enough for this particular target and we have to start somewhere.
=> Add automatic .gitignore setup to `fontship setup`

.github/workflows/build.yml, Dockerfile, requirements.txt
GFtools is [back with data files](https://github.com/googlefonts/gftools/releases/tag/v0.5.1) again (thanks again @m4rc1e).
=> Bump dependencies

Makefile.am, assets/en-US/cli.ftl, hooks/build, make-shell.zsh, rules/rules.mk, src/cli.rs, src/setup/mod.rs
- chore(i18n): Fix string mismatches observed while copying to CaSILE
- refactor(cli): Stop inverting shell flag meaning
- chore(build): Add autotools hook to test Rust code
- refactor(build): Organize makefile a bit
- chore(build): Drop unused release management target
- chore(build): Add automake hook to cleanup Cargo crates
- chore(docker): Normalize Docker Hub vs. local build systems
=> Implement lessons learned from CaSILE

Makefile.am, action.yml, build-aux/action-updater.js, hooks/build, package.json
- feat(actions): Run GitHub Action workflows with prebuilt containers
- chore(docker): Bump Docker base image
- chore(build): Automatically bump action version on release
- chore(deps): Bump developer-only tooling
=> Fixup usage from GitHub Container Registry
